info:
  version: 1.0.0
  description: Routing information for UE

ueRoutingInfo:
  - SUPI: imsi-2089300000003
    AN: upf1.free5gc.org
    PathList:
      - DestinationIP: 10.0.0.10
        DestinationPort: 8888
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF1

      - DestinationIP: 10.0.0.11
        DestinationPort: 9999
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF2

  - SUPI: imsi-2089300007486
    AN: upf2.free5gc.org
    PathList:
      - DestinationIP: 10.0.0.10
        DestinationPort: 8888
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF1

      - DestinationIP: 10.0.0.11
        DestinationPort: 9999
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF2
